name = "email-sender"
main = "worker.js"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]
send_email = [
    {name = "EMAIL"},
]

[vars]
SENDER_NAME = "TODO_UPDATE_SENDER_NAME"
AUTH_TOKEN = "TODO_UPDATE_AUTH_TOKEN"

[observability.logs]
enabled = true




