name = "free-email-sender-api"
main = "worker.js"
compatibility_date = "2023-10-04"
send_email = [
    {type = "send_email", name = "EMAIL", destination_address = "<YOUR_EMAIL>@example.com"},
]

[vars]
AUTH_TOKEN = "your_authorization_token"
